name = "hammpions"
main = "src/index.js"
compatibility_date = "2026-03-01"

[triggers]
crons = ["0 0 * * *"]

[[routes]]
pattern = "hammpions.com"
custom_domain = true
zone_name = "hammpions.com"

[[kv_namespaces]]
binding = "HAMMPIONS_KV"
id = "HAMMPIONS_KV_ID"
